<?php
return [
  'text-color' => 'black',
  'background-color' => 'white',
  'clickable-text-color' => '#111',
  'hover-clickable-text-color' => 'black',
  'scrollbar-hover-color' => '#e0e0e0',
  'scrollbar-active-color' => '#cccccc',
  'primary-button-text-color' => 'white',
  'primary-button-background-color' => '#3d3dee',
  'primary-button-cancel-background-color' => 'red',
  'primary-button-hover-background-color' => '#55f',
  'secondary-button-text-color' => 'black',
  'secondary-button-hover-background-color' => 'rgba(127, 127, 127, 0.5)',
  'header-text-color' => 'white',
  'header-background-color' => '#66f',
  'search-box-background-color' => '#3030de',
  'search-box-button-background-color' => '#3535f5',
  'navigation-background-color' => '#f2f2f2',
  'navigation-activated-background-color' => '#cacaca',
  'navigation-hover-background-color' => '#dadaf0',
  'profile-setting-background-color' => '#eeeeee',
  'profile-setting-avatar-background-color' => '#e0e0e0',
  'profile-setting-hover-background-color' => '#d7d7d7',
  'shadow-color' => 'rgba(100, 100, 100, 0.5)',
  'game-item-hover-background' => '#a9a9f5',
  'background-comment' => '#f2f2f2',
];
?>
