<?php
return [
  'user-password' => 's',
  'admin-password' => 's',
  'create-account' => 'sss',
  'user-account-existence' => 's',
  'game-existence' => 's',
  'game-genre-pair-existence' => 'ss',
  'list-games' => '',
  'list-users' => '',
  'list-genres' => '',
  'list-game-genre-pairs' => '',
  'add-game' => 'sss',
  'add-genre' => 'ss',
  'add-game-genre-pair' => 'ss',
  'add-user-playing-history' => 'ss',
  'user-info' => 's',
  'game-info' => 's',
  'genre-info' => 's',
  'get-all-games-by-genre' => 's',
  'get-all-genres-by-game' => 's',
  'get-history-by-user' => 's',
  'get-history-by-game' => 's',
  'update-admin-password' => 'ss',
  'update-user-profile' => 'ss',
  'update-genre-profile' => 'ss',
  'remove-all-games-from-genre' => 's',
  'remove-all-genres-from-game' => 's',
  'count-games' => '',
  'count-users' => '',
  'clear-games' => '',
  'clear-genres' => '',
  'clear-users' => '',
  'clear-admins' => '',
  'clear-history' => '',
  'clear-history-by-user' => 's',
  'clear-history-by-game' => 's',
  'clear-game-genre-pairs' => '',
  'delete-user' => 's',
  'delete-game' => 's',
  'delete-genre' => 's',
  'delete-game-genre-pair' => 'ss',
  'search-games' => 's',
];
?>
