<?php
return [
  'user-password' => 's',
  'admin-password' => 's',
  'create-account' => 'sss',
  'user-account-existence' => 's',
  'game-existence' => 's',
  'list-games' => '',
  'list-users' => '',
  'list-genres' => '',
  'add-game' => 'ssss',
  'add-genre' => 'ss',
  'user-info' => 's',
  'game-info' => 's',
  'update-user-profile' => 'ss',
  'count-games' => '',
  'count-users' => '',
  'clear-games' => '',
  'clear-genres' => '',
  'clear-users' => '',
  'clear-admins' => '',
  'delete-user' => 's',
  'search-games' => 's',
];
?>
